branch-defaults:
  default:
    environment: udagram-api-dev
deploy: 
  artifact: www/Archive.zip
global:
  application_name: udagram-api
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  workspace_type: Application
